name: reference_wrapper
description: A Dart package which simulates pass by reference feature.
version: 1.0.0
repository: https://github.com/maRci002/reference_wrapper
homepage: https://github.com/maRci002/reference_wrapper

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
